version: '3'

services:
  db:
    image: mongo:latest
    volumes:
      - .data/:/data/db
    ports:
      - 27017:27017

        #  mongo_export:
        #    image: mongo:latest
        #    links:
        #      - db
        #    volumes:
        #      - ./reviews:/seed-data
        #
        #
        #  mongo_seed:
        #    image: mongo:latest
        #    links:
        #      - db
        #    volumes:
        #      - ./reviews:/seed-data
        #    command:
        #       'bash -c "mongoimport --host db -d test -c machine --type json --file /seed-data/p_comentarios_classificacao_automatica.json --jsonArray"'
